### ISSUE TITLE
Manage links

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-sdk-api-specification#10]
Determine if there's anything that can be done with links that reference other `*.ipynb` files when hosted on GitHub.   It's possible that the links only work when in a running Jupyter notebook.  So we'll have to figure out how to document for:

1. Running Jupyter notebooks
1. GitHub hosted notebooks
1. Other documentation

![image (3)](https://user-images.githubusercontent.com/9219602/91446766-e0cadc80-e845-11ea-80cd-691b784e89dd.png)

Original discoverer:  @jbutcher21

**Comment by docktermj** [comment]
@SamMacy Work with @ryanbasile  to see if there's a solution to all of our documentation needs.

**Comment by SamMacy** [comment]
@docktermj I don't think this is possible as 1. How Github renders the notebooks makes it so that hyperlinking to specific parts of the notebook not possible. and 2. There is a way to change the links to link to different notebooks, but with the issue in # 1 it would only link to the top of it, and when using the notebooks it would not hyperlink to the notebooks but instead go to the notebook on github.
